
### Create freelance
POST http://localhost:8000/freelances
Content-Type: application/json

{
    "nom": "Johnatan Bayer",
    "email": "joh0na.bayer@domain.com",
    "skills": ["Python", "React", "Postman", "Angular"],
    "tjm": 130
}


### List all freelance
GET http://localhost:8000/freelances


### GET freelance by id
GET http://localhost:8000/freelances/2


### GET projects for freelance
GET http://localhost:8000/freelances/2/projets-compatibles


### Postuler a un projet
POST http://localhost:8000/freelances/3/postuler/3


### Create entreprise 
POST http://localhost:8000/entreprises
Content-Type: application/json

{
    "nom": "Microsoft",
    "secteur": "IT"
}


### List all entreprises
GET http://localhost:8000/entreprises


### GET entreprise by id
GET http://localhost:8000/entreprises/1


### Create project for entreprise 
POST http://localhost:8000/entreprises/1/projects
Content-Type: application/json

{
    "titre": "SoftTunes",
    "description": "Application opensource pour écouter de la musique gratuitement.",
    "skillsRequis": ["Python", "React", "Postman"],
    "budgetMaxTjm": 125,
    "entrepriseId": 1
}


### List projects for entreprise
GET http://localhost:8000/entreprises/1/projects


### List les candidats compatibles a un projet
GET http://localhost:8000/entreprises/1/projects/2/candidats-compatibles